services:
  app:
    build: .
    container_name: app
    depends_on:
      - osu-stats
    environment:
      - spring.data.mongodb.host=osu-stats
      - spring.data.mongodb.database=osu-stats

  osu-stats:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: always
    container_name: osu-stats-db